### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by DanteAlonsoHT** [hamdiheb/museum#2]
Great job! your project is fully responsive so far.

**Comment by hamdiheb** [comment]
Thank you dante

**Comment by IbrohimRasulov** [comment]
Good project 👍  And I recommend checking the top navbar on tablet size and making the main program section two-column on tablet mode, but anyway it is well structured

**Comment by hamdiheb** [comment]
Thank you ibrohim for you comment 
This issue has been fixed ,you can check live-demo again
